// Generated by Xata Codegen 0.27.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "blogs",
    columns: [
      { name: "blogTitle", type: "string" },
      { name: "articleOne", type: "text" },
      { name: "blogImages", type: "file[]" },
      { name: "createdAt", type: "datetime" },
      { name: "userId", type: "string", notNull: true, defaultValue: "null" },
      { name: "titePreview", type: "string" },
      { name: "articleOneTitle", type: "string" },
      { name: "articleImage", type: "file[]" },
      { name: "articleTwoTitle", type: "string" },
      { name: "articleTwo", type: "text" },
      { name: "ArticleThreeTitle", type: "string" },
      { name: "ArticleThree", type: "text" },
      { name: "ArticleFourTitle", type: "string" },
      { name: "ArticleFour", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Blogs = InferredTypes["blogs"];
export type BlogsRecord = Blogs & XataRecord;

export type DatabaseSchema = {
  blogs: BlogsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Mario-Angelov-s-workspace-hr2v9v.eu-central-1.xata.sh/db/f1antastic",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
